FROM node:20-alpine

ENV NEXT_TELEMETRY_DISABLED=1

WORKDIR /workspace/apps/web

COPY apps/web/package.json /workspace/apps/web/package.json
RUN npm install

COPY apps/web /workspace/apps/web

EXPOSE 3000

CMD ["npm", "run", "dev", "--", "--hostname", "0.0.0.0", "--port", "3000"]
